/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	fabedgev1alpha1 "github.com/fabedge/fabedge/pkg/apis/fabedge/v1alpha1"
	versioned "github.com/fabedge/fabedge/pkg/client/clientset/versioned"
	internalinterfaces "github.com/fabedge/fabedge/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/fabedge/fabedge/pkg/client/listers/fabedge/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CommunityInformer provides access to a shared informer and lister for
// Communities.
type CommunityInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CommunityLister
}

type communityInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCommunityInformer constructs a new informer for Community type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCommunityInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCommunityInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredCommunityInformer constructs a new informer for Community type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCommunityInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FabedgeV1alpha1().Communities().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FabedgeV1alpha1().Communities().Watch(context.TODO(), options)
			},
		},
		&fabedgev1alpha1.Community{},
		resyncPeriod,
		indexers,
	)
}

func (f *communityInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCommunityInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *communityInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&fabedgev1alpha1.Community{}, f.defaultInformer)
}

func (f *communityInformer) Lister() v1alpha1.CommunityLister {
	return v1alpha1.NewCommunityLister(f.Informer().GetIndexer())
}
