/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/fabedge/fabedge/pkg/apis/fabedge/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCommunities implements CommunityInterface
type FakeCommunities struct {
	Fake *FakeFabedgeV1alpha1
}

var communitiesResource = schema.GroupVersionResource{Group: "fabedge.io", Version: "v1alpha1", Resource: "communities"}

var communitiesKind = schema.GroupVersionKind{Group: "fabedge.io", Version: "v1alpha1", Kind: "Community"}

// Get takes name of the community, and returns the corresponding community object, and an error if there is any.
func (c *FakeCommunities) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Community, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(communitiesResource, name), &v1alpha1.Community{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Community), err
}

// List takes label and field selectors, and returns the list of Communities that match those selectors.
func (c *FakeCommunities) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CommunityList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(communitiesResource, communitiesKind, opts), &v1alpha1.CommunityList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CommunityList{ListMeta: obj.(*v1alpha1.CommunityList).ListMeta}
	for _, item := range obj.(*v1alpha1.CommunityList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested communities.
func (c *FakeCommunities) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(communitiesResource, opts))
}

// Create takes the representation of a community and creates it.  Returns the server's representation of the community, and an error, if there is any.
func (c *FakeCommunities) Create(ctx context.Context, community *v1alpha1.Community, opts v1.CreateOptions) (result *v1alpha1.Community, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(communitiesResource, community), &v1alpha1.Community{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Community), err
}

// Update takes the representation of a community and updates it. Returns the server's representation of the community, and an error, if there is any.
func (c *FakeCommunities) Update(ctx context.Context, community *v1alpha1.Community, opts v1.UpdateOptions) (result *v1alpha1.Community, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(communitiesResource, community), &v1alpha1.Community{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Community), err
}

// Delete takes name of the community and deletes it. Returns an error if one occurs.
func (c *FakeCommunities) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(communitiesResource, name), &v1alpha1.Community{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCommunities) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(communitiesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CommunityList{})
	return err
}

// Patch applies the patch and returns the patched community.
func (c *FakeCommunities) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Community, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(communitiesResource, name, pt, data, subresources...), &v1alpha1.Community{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Community), err
}
